name: Container Claus

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v[0-9]+.[0-9]+*'

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    env:
      MAKEFLAGS: -j3
    steps:
      - uses: actions/checkout@v3
      - name: Collect metadata for image
        id: meta
        run: |
          VERSION=$(echo ${{ github.ref }} | sed -e 's,.*/\(.*\),\1,')
          if [ "$VERSION" = "master" ]; then
            echo "tags=${{ github.repository }}:build-${GITHUB_RUN_NUMBER}"               >> $GITHUB_OUTPUT
          else
            echo "tags=${{ github.repository }}:$VERSION,${{ github.repository }}:latest" >> $GITHUB_OUTPUT
            echo "labels=org.opencontainers.image.version=$VERSION"                       >> $GITHUB_OUTPUT
          fi
          echo "args=revision=${GITHUB_SHA}" >> $GITHUB_OUTPUT
      - uses: docker/metadata-action@v4
        with:
          images: |
            ${{ github.repository }}
            ghcr.io/${{ github.repository }}
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Log in to Docker Hub
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          build-args: ${{ steps.meta.outputs.args }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le
